---
title: "Sliding window"
output: html_document
date: "2025-03-25"
---

```{r}
library(seqinr)
library(data.table)
library(dplyr)
library(depmixS4)
library(tidyr)
library(readr)

```
```{r}
#read in the fasta file
chr21 <- read.fasta("chr21.fa", forceDNAtolower = FALSE, strip.desc = TRUE)
```
```{r}
sliding_window <- function(sequence, window_size, step_size) {
  windows <- list() # list to store the windows
  for (i in seq(1, length(sequence) - window_size + 1, by = step_size)) {
    window <- sequence[i:(i + window_size - 1)]
    windows[[length(windows) + 1]] <- window
  }
  return(windows)
}
```
```{r}
windows <- sliding_window(chr21[[1]], 10000,10000)
#windows[2000]
```
```{r}
kmer_count <- function(window, k) {
  kmer_freq <- list()
  window_str <- paste(window, collapse = "")
  
  for (i in 1:(nchar(window_str) - k + 1)) {
    kmer <- substr(window_str, i, i+k-1)
    
    if (grepl("[a-zN]", kmer)) {
      next
    }
    
    if (kmer %in% names(kmer_freq)) {
      kmer_freq[[kmer]] <- kmer_freq[[kmer]] + 1
    } else {
      kmer_freq[[kmer]] <- 1
    }
  }
  return(kmer_freq)
}
```

```{r}
kmer_results <- lapply(windows, function(window) kmer_count(window, 2))
```

```{r}
windows_df <- data.frame(
  window_id = seq_along(windows),
  start_pos = seq(1, length(chr21[[1]]) - 10000 + 1, by = 10000),
  sequence = sapply(windows, paste, collapse = "")
)

kvalue = 2
windows_df$kmer_counts <- lapply(windows, function(w) kmer_count(w, k = kvalue))
```

```{r}
kmerdf <- windows_df[,4]
kmerdf1 <- as.data.frame(do.call(rbind, kmerdf))
all_kmers <- unique(unlist(lapply(kmerdf, names))) 
```

```{r}
kmerdf <- lapply(kmerdf, function(kmer_list) {
  if (is.null(kmer_list)) {
    kmer_list <- setNames(rep(0, length(all_kmers)), all_kmers)
  } else {
    kmer_list[setdiff(all_kmers, names(kmer_list))] <- 0
  }
  return(kmer_list[all_kmers])
})
```

```{r}
kmerdf1 <- as.data.frame(do.call(rbind, kmerdf))
class(kmerdf1$TG)
```
```{r}
# Ensure numeric values
kmerdf1 <- data.frame(lapply(kmerdf1, as.numeric))

# Compute relative frequencies (normalize by row sum)
kmerdf1_norm <- kmerdf1 / rowSums(kmerdf1)

# Replace NaN values (if any row had a total count of 0)
kmerdf1_norm[is.na(kmerdf1_norm)] <- 0
```



```{r}
fwrite(kmerdf1_norm, "~/my_data_norm.csv") 
```



